project_id = "qhiaxfwpcoqptfhhpjgs"

[functions.verify-pin]
verify_jwt = false

[functions.vault-upload]
verify_jwt = false

[functions.vault-files]
verify_jwt = false

[functions.vault-delete]
verify_jwt = false

[functions.vault-download]
verify_jwt = false

[functions.vault-rename]
verify_jwt = false
